### ISSUE TITLE
Store docker images on dockstore or synapse?

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/nf-hackathon-2019#8]
This is related to #6 - what is the motivation for storing docker images on synapse? To me there are the pros: security, requiring synapse login to get things going, but there are also cons, which are restricting the data to only those part of the hackathon. 

What do you think @allaway ? Do you think synapse is easier? better? I would have gone with dockstore but that's only based on familiarity.

**Comment by allaway** [comment]
We can and should make the docker images available to anyone registered with Synapse. I went with the Synapse Docker repo because to use any of the markdowns in the docker images, one has to have a Synapse login anyway. This way we can keep the docker images in the hackathon synapse project, so that they "live" in the same space as all of the other event material on Synapse.

The value added of these images are really only to provide an easy environment with which to use the hackathon data, outside of the context of these notebooks I think it makes more sense to start with a core docker container project like `rocker` or `jupyter-lab`.

**Comment by sgosline** [comment]
ok, that makes sense. thanks!
